routes/web.php
<?php

use App\Http\Controllers\ProductsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth']],function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('profile', [UsersController::class, 'profile']);
    Route::resource('products',ProductsController::class);
    Route::resource('users',UsersController::class)->middleware('role:admin');
    Route::get('/send_email/{id}', [UsersController::class, 'send_email'])->name('send_email')->middleware('role:admin');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'detail','created_by'
    ];

    public function user()
    {
        return $this->belongsTo(User::class,'created_by','id');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Datatables;
use Throwable;
use App\Models\Product;
use Illuminate\Support\Facades\Auth;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::with('user')->when(Auth::user()->role=="customer",function($q){
                return $q->where('created_by',Auth::user()->id);
            })->latest();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('created_by', function (Product $product) {
                    return $product->user->name;
                })
                ->addColumn('action', function ($row) {
                    $btn = '<div class="actions-a">
                    <a class="btn btn-primary btn-sm mr-1 edit"  data-id=' . $row->id . ' href="javascript:void(0)" title="Edit"><i class="fas fa-edit white cicon"></i> </a>
                    <a data-id=' . $row->id . ' class="btn btn-danger btn-sm mr-1 delete" href="javascript:void(0)" title="Delete"><i class="fas fa-trash-alt white cicon"></i></a>
                    </div>';
                    return $btn;
                })
                ->rawColumns(['created_by','action'])
                ->make(true);
        }
        return view('products.index')->with(['title'=>'Products']);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        try{
            $post=$request->all();
            $post['created_by']= Auth::user()->id;
            $request->id ?? 0;
            $product=Product::updateOrCreate(['id'=>$request->id],$post);
            $message=$request->id=='' ? 'Product successfully Inserted' : 'Product successfully Updated';
            return response()->json(['status' => true,'message' => $message]);
        }
        catch(Throwable $th){
            return response()->json(['status'=> false,'message' => $th->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        try{
            $data=Product::whereId($id)->firstorFail();
            return response()->json(['status'=>true,'message'=>"Successfully Fetched Data",'data'=>$data]);
        }
        catch(Throwable $th){
            return response()->json(['status'=>false,'message' => $th->getMessage()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Product::find($id)->delete();
        return response()->json(['status' => true, 'message' => 'Successfully Deleted Product']);
    }
}

resources/views/products/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <button name="add_product" id="add_product" class="btn btn-primary float-right">Add Product</button>

                        <table class="table table-bordered data-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Detail</th>
                                    <th>Created By</th>
                                    <th width="100px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                        <div class="modal fade" id="AddProductModal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Add Product</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form method="POST" enctype='multipart/form-data' name="addProduct" id="addProduct">
                                        <div class="modal-body">
                                            @csrf
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Name</label>
                                                        <input type="text" class="form-control" name="name"
                                                            placeholder="Enter name" id="name">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Detail</label>
                                                        <input type="text" class="form-control" name="detail"
                                                            placeholder="Enter detail" id="detail">
                                                    </div>
                                                </div>
                                                <input type="hidden" name="id" id="id">
                                            </div>

                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-default"
                                                data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary" id="addProductBtn">Save</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script>
            $(document).ready(function() {

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                //datatable
                var table = $('.data-table').DataTable({
                    processing: true,
                    responsive:true,
                    serverSide: true,
                    order : [],
                    ajax: "{{ route('products.index') }}",
                    order:[],
                    columns: [
                        {data: 'DT_RowIndex',name: 'DT_RowIndex',orderable: false,searchable: false},
                        {data: 'name'},
                        {data: 'detail'},
                        {data: 'created_by'},
                        {data: 'action',orderable: false,searchable: false},
                    ]
                });

                $('#add_product').click(function(){
                    $('#id').val('');
                    $('#addProduct')[0].reset();
                    $('#AddProductModal').modal('show');
                });

                //validate and form submit on add and update product
                $("#addProduct").validate({
                    rules: {
                        name: "required",
                        detail: "required",
                        // password: "required",
                        // image: "required"
                    },
                    messages: {
                        name: "Required name",
                        detail: "Required detail",
                        // password: "Required password",
                        // image: "Required image"
                    },
                    submitHandler: function(form,e) {
                        e.preventDefault();
                        $.ajax({
                            url: '{{ route("products.store") }}',
                            type: 'POST',
                            data: new FormData(form),
                            dataType: 'json',
                            processData: false,
                            contentType: false,
                            success: function (response) {
                                if(response.status==true){
                                    $('#AddProductModal').modal('hide');
                                    toastr.success(response.message);
                                    table.ajax.reload();
                                }
                                else{
                                    toastr.error(response.message);
                                }
                            },
                            error:function(){
                                $('#AddProductModal').modal('hide');
                                toastr.error('Please Reload Page');
                            }
                        });
                        return false;
                    }
                });

                //edit ajax
                $(document.body).on('click', '.edit', function () {

                    var $alertas = $('#addProduct');
                    $alertas.trigger('reset');
                    $alertas.find('.error').removeClass('error');
                    $alertas.find('.pac-target-input-error').removeClass('pac-target-input-error');

                    let id = $(this).attr('data-id');
                    $.ajax({
                        type: "GET",
                        url: "{{url('products')}}" + '/' + id,
                        dataType: "json",
                        success: function (response) {
                            if(response.status){
                                $('#name').val(response.data.name);
                                $('#id').val(response.data.id);
                                $('#detail').val(response.data.detail);
                                $('#AddProductModal').modal('show');
                                // toastr.success(response.message);
                                table.ajax.reload();

                            } else {
                                toastr.error(response.message);
                            }
                        },
                        error: function () {
                            $('#AddProductModal').modal('hide');
                            toastr.error('Please reload page');
                        }
                    });
                });

                //delete ajax
                $(document.body).on('click', '.delete', function () {
                    let id = $(this).attr('data-id');

                        $.ajax({
                            type: "DELETE",
                            url: "{{url('products')}}" + '/' + id,
                            dataType: "json",
                            success: function (response) {
                                toastr.success(response.message);
                                table.ajax.reload();
                            },
                            error: function () {
                                toastr.error('Please reload page');
                            }
                        });
                });
            });
        </script>
    @endpush
@endsection